name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore HD2-TS-Tool.sln

      - name: Build solution
        run: msbuild HD2-TS-Tool.sln /p:Configuration=Release

      - name: Find the real EXE
        id: findexe
        shell: pwsh
        run: |
          $exe = Get-ChildItem -Path "HD2-TS-Tool\bin\Release" -Filter "HD2-TS-Tool.exe" -Recurse | Select-Object -First 1
          if (-not $exe) {
            Write-Error "No HD2-TS-Tool.exe found in bin\\Release"
            exit 1
          }
          echo "EXE_PATH=$($exe.FullName)" >> $env:GITHUB_ENV

      - name: Upload EXE to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: HD2-TS-Tool ${{ github.ref_name }}
          files: ${{ env.EXE_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}