name: Build .NET Framework EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Restore NuGet packages
        shell: pwsh
        run: nuget restore "HD2-TS-Tool.sln"

      - name: Build with MSBuild
        shell: pwsh
        run: |
          # Find latest MSBuild installed
          $msbuild = & "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
          Write-Host "Using MSBuild at $msbuild"
          & $msbuild "HD2-TS-Tool.sln" /p:Configuration=Release

      - name: Zip Release folder
        shell: pwsh
        run: |
          $releasePath = "HD2-TS-Tool\bin\Release\*"
          $zipPath = "HD2-TS-Tool.zip"
          if (Test-Path $zipPath) { Remove-Item $zipPath }
          Compress-Archive -Path $releasePath -DestinationPath $zipPath

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: HD2-TS-Tool
          path: HD2-TS-Tool.zip
